name: Swift
on: [push]
jobs:

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Install dependencies
      run: brew install cairo fontconfig freetype
    - name: Build (Debug)
      run: swift build -c debug
    - name: Build (Release)
      run: swift build -c release
    - name: Test (Debug)
      run: swift test -c debug

  linux:
    name: Linux (${{ matrix.container }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: ["swift:latest"]
    container: ${{ matrix.container }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          libcairo2-dev libfreetype-dev libfontconfig-dev \
          fontconfig fonts-dejavu-core pkg-config
    - name: Build (Debug)
      run: swift build -c debug
    - name: Build (Release)
      run: swift build -c release
    - name: Test (Debug)
      run: swift test -c debug
